### ISSUE TITLE
TypeError: String.charCodeAt is not a function (in Chrome)

### ISSUE THREAD

**Issue by groovecoder** [jrconlin/WebPushDataTestPage#19]
STR:
1. Visit https://mozilla-services.github.io/WebPushDataTestPage/ in Chrome

Expected results:
Should see VAPID private and public keys shown in the page.

Actual results:
The keys are `undefined` and blank, respectively. And this error is in the console twice:

```
TypeError: String.charCodeAt is not a function
    at Object._str_to_array (https://mozilla-services.github.io/WebPushDataTestPage/vapid.js:68:31)
    at Object.url_atob (https://mozilla-services.github.io/WebPushDataTestPage/vapid.js:53:26)
    at webCrypto.exportKey.then.k (https://mozilla-services.github.io/WebPushDataTestPage/vapid.js:86:31)webCrypto.exportKey.then.catch.err @ vapid.js:110
```

**Comment by groovecoder** [comment]
We could call this fixed if we want - the page now shows a user-facing error instead of just the error in the console.

Or we could keep this open until Chrome implements this?

**Comment by jrconlin** [comment]
I'll close it for now, since i don't know when chrome will make 'raw' keys available. I'm trying to do the right thing and err on function, so when that is resolved, chrome should just work. 

thanks!
